### ISSUE TITLE
Unable to generate polymer

### ISSUE THREAD

**Issue by AmazingRise** [py-chemist/webapps#1]
It's a very good software, but I'm unable to generate any polymer.
When I input "polyethylene" in search box, it returns: C=C
And then I click convert, it produce such a result:
```LaTeX
\chemfig{
     % 1
    =% 2
}
```
And the final display is only a chemical bond.

**Comment by py-chemist** [comment]
The carbon atoms are not displayed by default. To turn on that feature, just select "Show Carbon" checkbox and click "Apply". You can also choose "Add" hydrogens from a drop-down menu to see bonds between carbons and hydrogens.
